# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rock_paper.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import random

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.headlabel = QtWidgets.QLabel(self.centralwidget)
        self.headlabel.setGeometry(QtCore.QRect(76, 60, 631, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(32)
        self.headlabel.setFont(font)
        self.headlabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.headlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.headlabel.setObjectName("headlabel")
        self.playercomboBox = QtWidgets.QComboBox(self.centralwidget)
        self.playercomboBox.setGeometry(QtCore.QRect(90, 300, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.playercomboBox.setFont(font)
        self.playercomboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.playercomboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.playercomboBox.setCurrentText("")
        self.playercomboBox.setObjectName("playercomboBox")
        self.playercomboBox.addItem("")
        self.playercomboBox.setItemText(0, "")
        self.playercomboBox.addItem("")
        self.playercomboBox.addItem("")
        self.playercomboBox.addItem("")
        self.comp_choicelabel = QtWidgets.QLabel(self.centralwidget)
        self.comp_choicelabel.setGeometry(QtCore.QRect(480, 300, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.comp_choicelabel.setFont(font)
        self.comp_choicelabel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comp_choicelabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.comp_choicelabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.comp_choicelabel.setLineWidth(76)
        self.comp_choicelabel.setText("")
        self.comp_choicelabel.setObjectName("comp_choicelabel")
        self.playerlabel = QtWidgets.QLabel(self.centralwidget)
        self.playerlabel.setGeometry(QtCore.QRect(120, 250, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.playerlabel.setFont(font)
        self.playerlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.playerlabel.setObjectName("playerlabel")
        self.complabel = QtWidgets.QLabel(self.centralwidget)
        self.complabel.setGeometry(QtCore.QRect(480, 250, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.complabel.setFont(font)
        self.complabel.setAlignment(QtCore.Qt.AlignCenter)
        self.complabel.setObjectName("complabel")
        self.resultlabel = QtWidgets.QLabel(self.centralwidget)
        self.resultlabel.setGeometry(QtCore.QRect(210, 390, 361, 81))
        font = QtGui.QFont()
        font.setFamily("Freestyle Script")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.resultlabel.setFont(font)
        self.resultlabel.setText("")
        self.resultlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.resultlabel.setObjectName("resultlabel")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(610, 490, 151, 20))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.yespushButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("yes"))
        self.yespushButton.setGeometry(QtCore.QRect(620, 510, 75, 23))
        self.yespushButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.yespushButton.setObjectName("yespushButton")
        self.nopushButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("no"))
        self.nopushButton.setGeometry(QtCore.QRect(700, 510, 75, 23))
        self.nopushButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.nopushButton.setObjectName("nopushButton")
        self.playButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.play("play"))
        self.playButton.setGeometry(QtCore.QRect(360, 290, 75, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.playButton.setFont(font)
        self.playButton.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.playButton.setObjectName("playButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    
    
    def play(self, pressed):
        choice = self.playercomboBox.currentText()
        comp = random.choice(["Rock","Paper","Scissor"])
        if pressed == "play":
            computer = self.comp_choicelabel.setText(str(comp))
            if choice == comp:
                result = "It's a Tie!"
            elif (choice == "Rock" and comp == "Scissor") or (choice == "Paper" and comp == "Rock") or (choice == "Scissor" and comp == "Paper"):
                result = "Player Wins!"
            else:
                result = "Player Lost!"
            self.resultlabel.setText(result)

    
    
    def press_it(self, pressed):
        if pressed == "yes":
           self.playercomboBox.setCurrentText("")
           self.comp_choicelabel.setText("")
           self.resultlabel.setText("")
        else:
            exit

    
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.headlabel.setText(_translate("MainWindow", "* Rock-Paper-Scissor *"))
        self.playercomboBox.setItemText(1, _translate("MainWindow", "Rock"))
        self.playercomboBox.setItemText(2, _translate("MainWindow", "Paper"))
        self.playercomboBox.setItemText(3, _translate("MainWindow", "Scissor"))
        self.playerlabel.setText(_translate("MainWindow", "PLAYER"))
        self.complabel.setText(_translate("MainWindow", "COMPUTER"))
        self.label.setText(_translate("MainWindow", "play again"))
        self.yespushButton.setText(_translate("MainWindow", "yes"))
        self.nopushButton.setText(_translate("MainWindow", "no"))
        self.playButton.setText(_translate("MainWindow", "play"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
